### ISSUE TITLE
Can't toggle/untoggle Freeze/Colorblind and...

### ISSUE THREAD

**Issue by mifunetoshiro** [pmaji/crypto-whale-watching-app#75]
With colorblind on, tooltips on ask side flash green/blue.

If Freeze is toggled, it would be great if the button changed to "Unfreeze"

**Comment by theimo1221** [comment]
The flashing is due to dash updating data, against periodic call in js to change color. If we increase the time of color change in JS we highly increase CPU load 
We tested it:
100ms Interval CPU increase from 4% to 6%
50 ms 4% to 8%
10 ms 4% to 12%
5 ms 4% to 18%
1 ms 4% to 50% resulting in lag wich increases flashing 😆 

The name changing can be done, will do it tomorrow.

**Comment by mifunetoshiro** [comment]
Ok, I see. and currently if I want to unfreeze, toggling doesn't work, I have to refresh the page.

**Comment by theimo1221** [comment]
It itself is refreshing side cause we can't restore updating interval routines cause they are from dash/ plotly

**Comment by theimo1221** [comment]
@mifunetoshiro does this solve your question, if so vote4close

**Comment by mifunetoshiro** [comment]
Ok, as long as the Freeze button gets renamed to "Unfreeze" when toggled, and clicking on "Unfreeze" refreshes the page so it starts refreshing again xD

**Comment by theimo1221** [comment]
Oh now I see, I didn´t noticed the error, was missing an set on true.

Fixed it in #80 and added changing of text

@mifunetoshiro  Thanks 😃

**Comment by mifunetoshiro** [comment]
@theimo1221 After activating colorblind, the button doesn't change to "Deactivate Colorblind." Also missing ; on line 38?

**Comment by theimo1221** [comment]
Nice spot with the ;
And check if you have newest js file in browser or still the old one 
If so clear cache to load new one

**Comment by mifunetoshiro** [comment]
Yea, it's the newest, still doesn't say "Deactivate Colorblind"
